[project]
authors = ["Mehmet Efe Akça <efeakca@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "EQTransformer"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
tensorflow = "~=2.5"
keras = "2.9.0"
#keras = ">=2.6.0,<3"
matplotlib = ">=3.5.3,<4"
pandas = "==1.4.3"
tqdm = "4.64.0"
h5py = "3.6.0"
obspy = "==1.3.0"
numpy = "==1.24"
pytest = ">=8.3.3,<9"
keyring = ">=25.5.0,<26"
pkginfo = ">=1.11.2,<2"
python = "==3.10.5"
jupyter = "1.0.0"

[pypi-dependencies]
eqtransformer = { path = "." }
#eqtransformer = { path = "." }
